[package]
name = "reaper-chunks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"

[dev-dependencies]
assert_float_eq = "1.1.3"
assert_matches = "1.5.0"